export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/v1/auth/login',
    REGISTER: '/v1/auth/register',
    LOGOUT: '/v1/auth/logout',
    VERIFY_EMAIL: '/v1/auth/verify-email',
    RESEND_VERIFICATION: '/v1/auth/resend-verification',
    FORGOT_PASSWORD: '/v1/auth/forgot-password',
    RESET_PASSWORD: '/v1/auth/reset-password',
  },
  // UC03 — Hồ Sơ Cá Nhân
  PROFILE: {
    GET: '/v1/profile',
    UPDATE: '/v1/profile',
    CHANGE_PASSWORD: '/v1/profile/password',
  },
  // [DEV ONLY] — endpoint này chỉ tồn tại khi backend chạy profile "dev" hoặc "local"
  DEV: {
    ACTIVATE_ACCOUNT: '/v1/dev/auth/activate',
  },
  BOOK: {
    LIST: '/books',
    DETAIL: '/books/:id',
  },
  BORROW: {
    LIST: '/v1/borrows',
    
    DETAIL: '/v1/borrows/:id',
    MY_HISTORY: '/v1/borrows/my-history',
    APPROVE: '/v1/borrows/:id/approve',
    REJECT: '/v1/borrows/:id/reject',
    CONFIRM_PICKUP: '/v1/borrows/:id/confirm-pickup',
    CANCEL: '/v1/borrows/:id/cancel',
    PENDING_APPROVAL: '/v1/borrows?status=PENDING_APPROVAL',
    RESERVED: '/v1/borrows?status=RESERVED',
    AWAITING_PICKUP: '/v1/borrows?status=AWAITING_PICKUP',
    APPROVED_WAITING_PAYMENT: '/v1/borrows?status=APPROVED_WAITING_PAYMENT',
    PICKUP_BY_CODE: '/v1/borrows/pickup/:pickupCode',
    LOOKUP_BY_CODE: '/v1/borrows/lookup/:pickupCode',
    CONFIRM_SHIPMENT: '/v1/borrows/:borrowId/confirm-shipment',
    RENTAL_RATES: '/v1/borrows/rental-rates',
    DEPOSIT_POLICIES: '/v1/borrows/deposit-policies',
  },
  WALLET: {
    GET: '/v1/wallet',
    TOP_UP: '/v1/wallet/top-up',
    WITHDRAW: '/v1/wallet/withdraw',
    TRANSACTIONS: '/v1/wallet/transactions',
  },
  PAYMENT: {
    CREATE: '/v1/payments/top-up',
    GET: '/v1/payments/:paymentCode',
    MOCK_CALLBACK: '/v1/payments/mock-callback',
    CANCEL: '/v1/payments/:paymentCode/cancel',
  },
  BOOK_RETURN: {
    REQUEST: '/v1/returns',
    PENDING: '/v1/returns/pending',
    CONFIRM: '/v1/returns/:borrowId/confirm',
    BULK_CONFIRM: '/v1/returns/bulk-confirm',
    RETURN_REQUESTED: '/v1/borrows/return-requested',
    RETURN_ISSUES: '/v1/borrows/return-issues',
    CREATE_SHIPMENT: '/v1/borrows/:borrowId/return-shipment',
    RETRY_RETURN: '/v1/borrows/:borrowId/retry-return-shipping',
    RESOLVE_LOST: '/v1/borrows/:borrowId/resolve-return-lost',
  },
  FINE: {
    LEVELS: '/v1/fine-levels',
    MY_FINES: '/v1/fines/my-fines',
    PAY: '/v1/fines/:id/pay',
    PENDING_CONFIRM: '/v1/fines/pending-confirmation',
    DETAIL: '/v1/fines/:fineId',
    CONFIRM: '/v1/fines/:fineId/confirm',
    REJECT: '/v1/fines/:fineId/reject',
  },
  USER: {
    LIST: '/users',
    DETAIL: '/users/:id',
  },
  ADMIN_USER: {
    LIST: '/v1/admin/users',
    STATUS: '/v1/admin/users/:id/status',
    ROLE: '/v1/admin/users/:id/role',
  },
  REPORT: {
    DASHBOARD: '/reports/dashboard',
    DETAILED: (type) => `/reports/${type}`,
    EXPORT: '/reports/export',
    EXPORT_STATUS: (id) => `/reports/export/${id}/status`,
    EXPORT_DOWNLOAD: (id) => `/reports/export/${id}/download`,
    EXPORT_RETRY: (id) => `/reports/export/${id}/retry`,
  },
  SHIPPING: {
    LIST: '/shipping',
    TRACK: '/shipping/:id/track',
    CREATE_SHIPMENT: '/v1/borrows/:borrowId/shipments',
    AWAITING_SHIPMENT: '/v1/borrows?status=AWAITING_SHIPMENT',
  },
  DELIVERY: {
    CONFIRM: '/v1/borrows/:borrowId/confirm-delivery',
    REPORT_ISSUE: '/v1/borrows/:borrowId/report-issue',
    HANDLE_ISSUE: '/v1/borrows/:borrowId/handle-issue',
    ISSUES: '/v1/borrows/delivery-issues',
  },
  MOOD: {
    PUBLIC_LIST: '/v1/moods/public',
    LIST: '/v1/moods',
    CREATE: '/v1/moods',
    UPDATE: '/v1/moods/:id',
    DELETE: '/v1/moods/:id',
  },
  RECOMMENDATION: {
    LIST: '/v1/recommendations',
  },
  READING_PATH: {
    GENERATE: '/v1/reading-paths/generate',
    SAVE: '/v1/reading-paths',
  },
}
